apiVersion: run.tanzu.vmware.com/v1alpha1      #TKG API endpoint
kind: TanzuKubernetesCluster                   #required parameter
metadata:
  name: tkc-argo-01                            #cluster name, user defined
  namespace: argocd                            #supervisor namespace
spec:
  distribution:
    version: v1.21                             #resolved kubernetes version
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: best-effort-small                 #vmclass for control plane nodes
      storageClass: nfs-storage-policy         #storageclass for control plane
    workers:
      count: 1                                 #number of worker nodes
      class: best-effort-small                 #vmclass for worker nodes
      storageClass: nfs-storage-policy         #storageclass for worker nodes
  settings:
    storage:
      defaultClass: nfs-storage-policy
    network:
      cni:
        name: antrea
